### PR TITLE
Add build instructions for OS X

### PR DESCRIPTION
**Pull request by tdhopper**

### CODE REVIEW

**Comment by ariddell** [comment]
These are the build instructions for Linux as well (although I'm not sure if ``pip install -e .`` should be preferred?)

**Comment by tdhopper** [comment]
@ariddell I'm not clear on the differences

**Comment by ariddell** [comment]
I think they are the same thing now (https://pythonhosted.org/setuptools/setuptools.html#development-mode).

Does develop run ``python setup.py build_ext --inplace``? I think one might need to run that (in addition to rerunning ``cython``) if one makes any changes cython files.

**Comment by tdhopper** [comment]
Not sure...

**Pull request merged**
